### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by srnden** [dmstr/docker-yii2-app#5]
hi, i have this error

```
$ docker-compose up -d
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 118, in perform_command
  File "compose\cli\command.py", line 37, in project_from_options
  File "compose\cli\command.py", line 91, in get_project
  File "compose\config\config.py", line 385, in load
  File "compose\config\config.py", line 484, in load_services
  File "compose\config\config.py", line 463, in build_services
  File "compose\config\config.py", line 448, in build_service
  File "compose\config\config.py", line 715, in process_service
  File "compose\config\config.py", line 1131, in resolve_volume_paths
  File "compose\config\config.py", line 1150, in resolve_volume_path
  File "ntpath.py", line 311, in expanduser

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 9: ordinal not in range(128)
Failed to execute script docker-compose
```
```
$ docker --version
Docker version 17.10.0-ce, build f4ffd25
$ docker-compose --version
docker-compose version 1.16.1, build 6d1ac219
```
OS Windows 10

**Comment by schmunk42** [comment]
Can you run `docker-compose config`?

If yes, could you try `FROM dmstr/php-yii2:7.1-fpm-3.1` (Debian) in your `Dockerfile`...

**Comment by srnden** [comment]
`docker-compose config` same error

**Comment by schmunk42** [comment]
Looks like some [`python` issue](https://www.google.de/search?ei=0ugDWoKFEMnGkwXIs6TACA&q=UnicodeDecodeError%3A+%27ascii%27+codec+can%27t+decode++ordinal+not+in+range&oq=UnicodeDecodeError%3A+%27ascii%27+codec+can%27t+decode++ordinal+not+in+range&gs_l=psy-ab.3...19916.28571.0.28884.0.0.0.0.0.0.0.0..0.0....0...1.1.64.psy-ab..0.0.0....0.Pf_c4A8oYWs)?!
Or [docker-compose](https://github.com/docker/compose/search?q=UnicodeDecodeError&type=Issues&utf8=%E2%9C%93)?

Can you trace down which line in the `docker-compose.yml` file creates the error?

**Comment by schmunk42** [comment]
related https://github.com/docker/compose/issues/3806
